version: 2
updates:
  - package-ecosystem: "npm"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
    groups:
      react:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
      storybook:
        applies-to: version-updates
        patterns:
          - "@storybook/*"
      fontsource:
        applies-to: version-updates
        patterns:
          - "@fontsource/*"
      mui:
        applies-to: version-updates
        patterns:
          - "@mui/*"
  - package-ecosystem: "github-actions"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
